<?php
   /**
    *  Crypto Monitor – Miners File
    * ==============================
    *  Created 2017-06-09
    *
    *  This script handles hash data logged from the XMR-Stak miner
    *  It parses data on the format:
    *
    *  ## BEGIN REPORT ##
    *  2017-06-09 20:30:01 Host CPU
    *  |  0 | 43.5 | 43.5 | 43.5 |  1 | 43.4 | 43.4 | 43.4 |
    *  |  2 | 38.3 | 38.4 | 38.3 |  3 | 43.5 | 43.5 | 43.5 |
    *  |  4 | 43.4 | 43.4 | 43.4 |  5 | 60.0 | 59.9 | 59.8 |
    *
    *  The report is generated by a bash script:
    *  #!/bin/bash
    *
    *  echo "## BEGIN REPORT ##"
    *
    *  LOGFILE=/path/to/logs/XMR-Stak-CPU-LeelaCP.log
    *  LASTMOD=$(date -r $LOGFILE '+%Y-%m-%d %H:%M:%S')
    *
    *  echo "$LASTMOD Host CPU"
    *  tail -n100 $LOGFILE | grep "^[\|].*" | tail -n6
    */

    $bMain = true;
    require_once("includes/init.php");

    // Page Header
    require_once("includes/header.php");

    $sRaw = shell_exec("cat '".$cMinerLog."'/*");

    $dTot1 = 0.0;
    $dTot2 = 0.0;
    $dTot2 = 0.0;
    $nTotC = 0;
    echo "<table class='list-table'>\n";
    $aReports = explode("## BEGIN REPORT ##", trim($sRaw));
    foreach($aReports as $sReport) {
        $aLines = explode("\n", trim($sReport));
        if(count($aLines) == 0) continue;
        $aHeader = explode(" ", $aLines[0]);
        if(count($aHeader) != 4) continue;
        $sDate = $aHeader[0];
        $sTime = $aHeader[1];
        $sHost = $aHeader[2];
        $sUnit = $aHeader[3];
        echo "<tr class='list-section'>";
            echo "<td colspan=4>".$sUnit." on ".$sHost."</td>";
        echo "</tr>\n";
        echo "<tr class='list-head'>";
            echo "<td>Core</td>";
            echo "<td class='right'>2.5 sec</td>";
            echo "<td class='right'>60 sec</td>";
            echo "<td class='right'>15 min</td>";
        echo "</tr>\n";

        $oddEven = 0;
        $nCores  = 0;
        $dSum1   = 0.0;
        $dSum2   = 0.0;
        $dSum3   = 0.0;
        for($i=1; $i<count($aLines); $i++) {
            $aRows = explode("|", $aLines[$i]);
            if(count($aRows) > 4) {
                $dSum1 += floatval($aRows[2]);
                $dSum2 += floatval($aRows[3]);
                $dSum3 += floatval($aRows[4]);
                echo "<tr class='list-row ".($oddEven%2==0?"even":"odd")."'>";
                    echo "<td class='right'>".$aRows[1]."</td>";
                    echo "<td class='right'>".$aRows[2]." H/s</td>";
                    echo "<td class='right'>".$aRows[3]." H/s</td>";
                    echo "<td class='right'>".$aRows[4]." H/s</td>";
                echo "</tr>\n";
                $nCores++;
                $oddEven++;
            }
            if(count($aRows) > 9) {
                $dSum1 += floatval($aRows[6]);
                $dSum2 += floatval($aRows[7]);
                $dSum3 += floatval($aRows[8]);
                echo "<tr class='list-row ".($oddEven%2==0?"even":"odd")."'>";
                    echo "<td class='right'>".$aRows[5]."</td>";
                    echo "<td class='right'>".$aRows[6]." H/s</td>";
                    echo "<td class='right'>".$aRows[7]." H/s</td>";
                    echo "<td class='right'>".$aRows[8]." H/s</td>";
                echo "</tr>\n";
                $nCores++;
                $oddEven++;
            }
        }
        $dTot1 += $dSum1;
        $dTot2 += $dSum2;
        $dTot3 += $dSum3;
        $nTotC += $nCores;
        echo "<tr class='list-foot'>";
            echo "<td class='right'>".$nCores."</td>";
            echo "<td class='right'>".number_format($dSum1,1,".","")." H/s</td>";
            echo "<td class='right'>".number_format($dSum2,1,".","")." H/s</td>";
            echo "<td class='right'>".number_format($dSum3,1,".","")." H/s</td>";
        echo "</tr>\n";
        echo "<tr class='list-row right'>";
            echo "<td colspan=4>".$sDate." ".$sTime."</td>";
        echo "</tr>\n";
    }
    echo "<tr class='list-section'>";
        echo "<td colspan=4>Totals</td>";
    echo "</tr>\n";
    echo "<tr class='list-foot'>";
        echo "<td class='right'>".$nTotC."</td>";
        echo "<td class='right'>".number_format($dTot1,1,".","")." H/s</td>";
        echo "<td class='right'>".number_format($dTot2,1,".","")." H/s</td>";
        echo "<td class='right'>".number_format($dTot3,1,".","")." H/s</td>";
    echo "</tr>\n";
    echo "</table>\n";

    require_once("includes/footer.php");
?>
